# Generated by Django 4.2.3 on 2023-08-01 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
