# Generated by Django 4.2.3 on 2023-07-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=250)),
                ('content', models.TextField(default=None)),
                ('tags', models.CharField(default=None, max_length=300)),
                ('sources', models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
