# Generated by Django 4.2.4 on 2023-08-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_news_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='id',
        ),
        migrations.AddField(
            model_name='new',
            name='new_id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
