# Generated by Django 4.2.4 on 2023-08-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_new_id_new_new_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='new_id',
        ),
        migrations.AddField(
            model_name='new',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
