# Generated by Django 4.2.4 on 2023-08-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_new_new_id_new_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='sources',
            new_name='source',
        ),
    ]
